# Generated by Django 2.2.5 on 2020-01-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200127_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_mehtod',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
