# Generated by Django 2.2.5 on 2019-12-23 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20191223_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hosts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
