# Generated by Django 2.2.5 on 2020-01-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20191223_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='facilities',
        ),
    ]
